### ISSUE TITLE
FERR-89 - Sample the database for query and view fields

### ISSUE THREAD

**Issue by nlaprell** [marklogic-community/data-explorer#11]
**Original Reporter:**  @damonfeldman  
**Created:** 	12/Dec/17 9:29 AM
# Description
Instead of only supporting document upload, we should allow the database itself to be sampled for representative documents, so we get the combined set of all fields (for a given root or distinguishing element) for the query and view builders.

A "data visualizer" tool the SE group uses has one already, written by Ryan Dew. Ideally we will componentize that code so it can be shared between ferret and data visualizer.

# Comments

**Comment by josvr** [comment]
This would be a ubercool feature. Nice brainteaser if you want to implement this really well. Good luck.
