### ISSUE TITLE
Scroll to results when searching

### ISSUE THREAD

**Issue by cskeefer** [marklogic-community/data-explorer#113]
In the case that there are a lot of search fields the results area is not visible when when you have scrolled down to enter search values and press the Search button. Because you can't see the results area, you don't know when the search is complete. We could remedy this by scrolling to the top when the search completes. Other ideas welcome but seems like we need some indicator that the search is complete.

**Comment by nlaprell** [comment]
Updated to scroll to 0,0 when the search is executed.

**Comment by nlaprell** [comment]
Merged into Master.
