### ISSUE TITLE
FERR-38 - Make it easier to build a query/view (form)

### ISSUE THREAD

**Issue by nlaprell** [marklogic-community/data-explorer#12]
**Original Reporter:**  @markschiffner  
**Created:** 	03/Aug/17 2:50 PM
# Description
As a wizard user to create query and views in a clear and intuitive manner.

# Comments
*None*

**Comment by josvr** [comment]
Will be picked up by me as part of FERR-90

**Comment by josvr** [comment]
Assigned to Mark/Damon. This is fixed in CRUD #13 which is now pending merging. Please close this message once confirmed.

**Comment by markschiffner** [comment]
Merged
