### ISSUE TITLE
FERR-90 - CRUD for queries and views

### ISSUE THREAD

**Issue by nlaprell** [marklogic-community/data-explorer#13]
**Original Reporter:**  @markschiffner  
**Created:** 13/Jan/18 8:00 PM
# Description
Have CRUD (Create, Read, Update, Delete) management on the UI for query and views.

Currently we can only create queries through the UI.

Any updates and deletes would have to be done via QConsole.

# Comments
@markschiffner  added a comment - 13/Jan/18 8:01 PM
This can be worked in conjunction with FERR-38 (#12).  It can also be broken down into multiple tickets if needed.

**Comment by josvr** [comment]
As discussed with Vijay I will pick up

**Comment by josvr** [comment]
I am working on this now

**Comment by josvr** [comment]
Pull request. Please validate pull request, merge, and close this one.

**Comment by nlaprell** [comment]
I've spend some time testing from the UI end and have the following recommendations so far:

1. Debug information is still being logged to the console in adhoc-wizard.controller.js lines 459 & 460, as well as crud.controller.js lines 136 & 139.
2. Clicking next after selecting fields when creating a query throws an error to the console: "An invalid form control with name='' is not focusable"
3. Clicking next after selecting fields when creating a view throws an error to the console: "TypeError: cannot read property 'pathname' of undefined: detail.controller.js line 8"
4. For all buttons, I would suggest using standard UI button location where the action button (next, continue, save, submit, etc) is on the right and the cancel button (back, cancel, exit, etc) is on the left. Usually, the button for the most common or safest path is on the far right.
5. Most of our buttons seem to have an ellipsis, which should only ever indicate truncation. These should be removed.
6. Input fields, specifically the bookmark, query, and view names, should be limited in length to prevent display issues. 50 characters would be my recommended max.
7. I was able to get the query creation to submit without selecting a query name (the insert button was active). I have not since been able to reproduce, so that may be difficult to track down.
8. Suggest renaming "Insert" to "Save"
9. There is not notification of the query/view being saved aside from being redirected back to the list. This is very minor, but would be nice to have an indication that the operation was successful. A green message such as "Your query [queryname] was saved." above the paging control that disappears after 10 seconds would be nice.
10. Saving a view with a comma in the name causes a 500 error when using it in a search. It throws an XDMP-UNEXPECTED for unexpected Comma that is coming from api-adhoc-search.xqy on line 15.

**Comment by josvr** [comment]
Thanks for you valuable input @nlaprell . I will address them in following commits. The logging was related to serverside logging, however indeed we need to remove debug logging client side as well. I cannot guarantee I will fix all issues. I see some issues as nice to have or more or less extra features (such as the save successful).

**Comment by markschiffner** [comment]
Closed with FERR-90 merge
