### ISSUE TITLE
FERR-49 - Automatic version update

### ISSUE THREAD

**Issue by nlaprell** [marklogic-community/data-explorer#16]
**Original Reporter:**  @markschiffner  
**Created:** 	25/Aug/17 8:05 AM
# Description
Need automatic revision number update based on checkin.
At minimum, we should have a file with the revision that we update and tag the baseline.
Currently UI says v0.1.0.

**Comment by markschiffner** [comment]
We need to check the version numbers.  Did the beta go out as release 0.1.0 or 0.9.0?  Pradeep Kumar in ticket #101 refers to the beta being 0.9.

**Comment by nlaprell** [comment]
Merged to Master.
