### ISSUE TITLE
Excel Export is giving wrong Data

### ISSUE THREAD

**Issue by chaitanya447** [marklogic-community/data-explorer#164]
Hi,

When i am exporting the view Data in excel report, i see the data is wrongly formatted. The second column values are showing for the first column values. Could you please take a look at this issue?

Thanks,
Chaitanya

**Comment by markschiffner** [comment]
Yes, thank you Chaitanya,  we will take a look at it.

**Comment by KetanDubey** [comment]
Hi Chaitanya/Mark,
Its been fixed,replace your search-lib with below one:
[search-lib.txt](https://github.com/marklogic-community/data-explorer/files/2192724/search-lib.txt)

**Comment by markschiffner** [comment]
Fixed, will deploy with v0.11
