### ISSUE TITLE
Not all databases showing

### ISSUE THREAD

**Issue by nizdobs** [marklogic-community/data-explorer#167]
When I'm selecting my database the data explorer isn't displaying a list of all databases. See the attached files for the list of all databases on my localhost environment vs. those that the data explorer shows me. Why can't I select the Documents database?

I'm logging in as admin/admin and the jar file is version data-explorer-0.10.jar

<img width="786" alt="screen shot 2018-08-01 at 16 09 55" src="https://user-images.githubusercontent.com/647414/43546020-8d019f5c-95a5-11e8-82d2-4cbf8c7364a9.png">
<img width="467" alt="screen shot 2018-08-01 at 16 09 35" src="https://user-images.githubusercontent.com/647414/43546025-901931e6-95a5-11e8-91d8-b88ceb52aef0.png">

**Comment by markschiffner** [comment]
Yes, it lists databases that have an app server to connect to. We intentionally do not want to lists all the databases. If you have an additional requirement, please let us know. We will add documentation on the Readme to clarify.

**Comment by nizdobs** [comment]
Yes, that absolutely makes sense. But it should be documented accordingly.
