### ISSUE TITLE
cannot login on a load balance environment

### ISSUE THREAD

**Issue by leond08** [marklogic-community/data-explorer#189]
I have 8 nodes of MarkLogic and those are on a load balance set up.
After installation, I log in as wizard-user, password is the default password then I got an error 
saying "401 (User is not authorized)."

**Comment by masyukun** [comment]
Hi @leond08 

It sounds like you might be running into a known issue with load balancing with MarkLogic described in this KB article. 

>  It is important that the load balancer is configured to use sticky sessions when interacting with MarkLogic Server so that existing sessions always communicate with the same host.

https://help.marklogic.com/Knowledgebase/Article/View/32/15/load-balancing-in-marklogic

**Comment by markschiffner** [comment]
If this did not resolve your issue, please let us know.
