### ISSUE TITLE
Logging in as admin does not work

### ISSUE THREAD

**Issue by damonfeldman** [marklogic-community/data-explorer#2]
From an early adopter (Scott): 

"I got it to run but when I login it doesn’t take me to the wizard page.  If I explicitly ask for the wizard page it gives it to me but when I ask to create a query after selecting an xml file it says it can’t login."

This is probably because the admin user does not have the specific "data-explorer" roles needed, and those roles are explicitly checked.

We should report to people that they are missing the required role if that check fails, rather than the more generic login failure.

**Comment by josvr** [comment]
I will pick this up.

**Comment by josvr** [comment]
Admin gets the same approach as in query console: can do everything. This will make adoption easier.

**Comment by josvr** [comment]
This is now fixed in the latest commit of FERR-90

**Comment by josvr** [comment]
Fixed in #13
