### ISSUE TITLE
FERR-70 - Highlight search terms in results

### ISSUE THREAD

**Issue by nlaprell** [marklogic-community/data-explorer#24]
**Original Reporter:**  @markschiffner  
**Created:** 	27/Nov/17 8:05 AM
# Description
*None*

# Comments
@mfgumban added a comment - 14/Jan/18 11:00 PM
Added matches and highlights to adhoc search endpoint
Added highlights to columns
Added "All Matches" column to show matches on elements not projected as view columns

**Comment by markschiffner** [comment]
Current implementation highlights if term put in search bar.
I believe the element display was broken during development.
Need to have highlighting for element searches as well. 
I will create new ticket.
