### ISSUE TITLE
FERR-59 - Fix error logging

### ISSUE THREAD

**Issue by nlaprell** [marklogic-community/data-explorer#25]
**Original Reporter:**  @markschiffner  
**Created:** 	09/Nov/17 1:49 PM
# Description
Make sure error messages go to the ML errorlog.

Many, most errors are being ignored.

**Comment by josvr** [comment]
We close this issue.  We will address this as part of #62 . I updated the text of that one.

**Comment by markschiffner** [comment]
Merged with FERR-90 merge
