### ISSUE TITLE
FERR-83 - Wizard: limit elements when creating view

### ISSUE THREAD

**Issue by nlaprell** [marklogic-community/data-explorer#29]
**Original Reporter:**  @cskeefer  
**Created:** 	28/Nov/17 6:40 PM
# Description
When a view is created in lib-adhoc-create:create-edit-view, it is limited to 15 elements. We should prevent the user from specifying more than 15.

**Comment by josvr** [comment]
No the real solution is that we make the number of elements dynamic. There is a limit of 250 and 15 in the current branch. We simply need to add a counter which tells how much elements are filled. I will take this up

**Comment by markschiffner** [comment]
Integrated.  Created new ticket #75 to address UI inconsistencies with #36
