### ISSUE TITLE
FERR-27 - Root element query not identifying correct element

### ISSUE THREAD

**Issue by nlaprell** [marklogic-community/data-explorer#33]
**Original Reporter:**  @rjkennedy98  
**Created:** 	02/May/17 11:50 AM
# Description
It will not take the root element - instead will take the second element.
/ind:individual/ind:individual:src ->

cts:element-query( xs:QName("individual:src"),
...
)

**Comment by josvr** [comment]
This is fixed in the latest push of the FERR-90 branch. Please close after validation.

**Comment by markschiffner** [comment]
Closed with FERR-90 merge
