### ISSUE TITLE
FERR-37 - Multiple Views/Queries found

### ISSUE THREAD

**Issue by nlaprell** [marklogic-community/data-explorer#34]
**Original Reporter:**  @rjkennedy98   
**Created:** 		17/Jul/17 6:42 PM
# Description
If you create two view/queries with the case-insensitive names they will be created, but when you search it won't work.
e.g. iNDIVIDUAL vIEW and individual view

**Comment by josvr** [comment]
This is fixed by the CRUD. Please check and close if that is the case. Else provide reproduction details here.

**Comment by markschiffner** [comment]
Closed with FERR-90 merge
