### ISSUE TITLE
FERR-64 - Import/Export of Queries and views

### ISSUE THREAD

**Issue by nlaprell** [marklogic-community/data-explorer#35]
**Original Reporter:**  @markschiffner  
**Created:** 	15/Nov/17 6:00 AM
# Description
There are gradle tasks for import (importData) and export (exportData) of the queries and views.

We have had numerous code updates recently and it seems that this is no longer exporting the data.  

> gradle exportData

**Comment by vjsaradhi** [comment]
Mark, the importData and exportData tasks were renamed to importQueriesAndViews and exportQueriesAndViews and seem to be workn=ing as expected. Please verify and close the issue,

**Comment by josvr** [comment]
This one is broken as of CRUD #13, since there we store the query/view in 1 XML. I will pick this one up.

**Comment by markschiffner** [comment]
Closed with FERR-90 merge
