### ISSUE TITLE
FERR-61 - Automate setting up new database using Adhoc Wizard

### ISSUE THREAD

**Issue by nlaprell** [marklogic-community/data-explorer#36]
**Original Reporter:**  @markschiffner  
**Created:** 	10/Nov/17 7:39 AM
# Description
Allow user/developer that is generating a query/view to select document from the database:

1. Random document
2. Via collection
3. Via URI
4. Filesystem (current)

Replacing FERR-4, which was set up as sub-task.

**Comment by markschiffner** [comment]
Integrated.  Created new ticket #75 to address UI inconsistencies with #73
