### ISSUE TITLE
FERR-20 - Bookmark/Save Queries

### ISSUE THREAD

**Issue by nlaprell** [marklogic-community/data-explorer#37]
**Original Reporter:**  @markschiffner  
**Created:** 	29/Apr/17 12:37 PM
# Description
Allow users to save query/views as bookmarks on the menu bar for easy access.
These reports can be directly on the menu bar or as setup as drop downs.
Design considerations:

- full crud for report definition
- handling underlying query/view deletion
- menu size/overflow
- dropdown size/overflow
- should be able to jump to report creation from wizard or step in wizard
- should be able to handle user vs global only definitions

# Comments
@rjkennedy98 added a comment - 02/May/17 11:52 AM
I think query-based bar charts and pie charts would be pretty easy to implement. You could even re-use the existing query templates to make it easier.

**Comment by josvr** [comment]
Implemented as part of FERR-90, GitHub #13 . Please close this one once the FERR-90 pull request is merged.

**Comment by markschiffner** [comment]
Closed with FERR-90 merge
