### ISSUE TITLE
FERR-30 - Pull all of the docTypes from a database to use for creation of queries

### ISSUE THREAD

**Issue by nlaprell** [marklogic-community/data-explorer#40]
**Original Reporter:**  Greg Meddles 
**Created:** 	22/Jun/17 3:22 PM
# Description
As a configuration user, I would like to see a list of all of the document types that are available to me (based on security) so that I can immediately jump into creating queries and views based on the document in my databases

**Comment by mfgumban** [comment]
Related to #11 .
