### ISSUE TITLE
FERR-92 - Provide clear messages on query/view definition

### ISSUE THREAD

**Issue by nlaprell** [marklogic-community/data-explorer#53]
**Original Reporter:**  @markschiffner  
**Created:** 15/Jan/18 8:09 AM
# Description
Add messages on the screen(s) to create query and view of the difference:
- Query: Choose elements you would like to query against
- View: Choose elements you would like to see in output

**Comment by josvr** [comment]
We will address this in CRUD. So I assign this one to myself.

**Comment by josvr** [comment]
This is addressed by CRUD. Please check branch FERR-90, see issue #13  . Please close this issue if you agree.

**Comment by josvr** [comment]
Well, I close it myself, as I was the creator of this issue anyway.
