### ISSUE TITLE
Convert xdmp:log messages to trace events

### ISSUE THREAD

**Issue by markschiffner** [marklogic-community/data-explorer#62]
Migrate the xdmp:log messages to use trace events, other errors are completely ignored.

**Comment by josvr** [comment]
Will fix together with #25 "FERR 59"

**Comment by rjrudin** [comment]
My hunch is one trace event - "data-explorer" ought to do it. I know ML has a lot of OOTB trace events with camel casing and spaces, but I prefer "worm case" for custom trace events, seems more consistent with e.g. XQuery naming.

**Comment by josvr** [comment]
This fixed in the latest FERR-90 branch. Please close this issue after validation.

**Comment by markschiffner** [comment]
Closed with FERR-90 merge
