### ISSUE TITLE
FERR-55 - Support JSON

### ISSUE THREAD

**Issue by nlaprell** [marklogic-community/data-explorer#8]
**Original Reporter:**  @rjkennedy98  
**Created:** 27/Oct/17 8:02 AM
# Description
Support views, queries and detail for JSON documents.

# Comments
@josvr  added a comment - 09/Nov/17 1:37 PM
I will pick this one up

@josvr  added a comment - 15/Nov/17 6:06 AM
Split out in FERR-65 and FER-66

**Comment by josvr** [comment]
Pull request created for branch FERR-65. Fixed once merged with master

**Comment by josvr** [comment]
If ferr 66 and 65 are status highest then this is also.

**Comment by josvr** [comment]
Implemented and merged in master
