### ISSUE TITLE
CRUD has some basic confirm/alert boxes

### ISSUE THREAD

**Issue by josvr** [marklogic-community/data-explorer#83]
After CRUD is merged (FERR-90, #13 ), the sourcetree will contain some basic Javascript dialogs (search for "alert" and "confirm") eg if you try to insert a view with a name which already exists, or some confirm dialogs if you try to delete a view/query. 

It would be nice to convert those basic Javascript dialog into native Angular (modal) dialogs.

**Comment by nlaprell** [comment]
Merged into master
