### ISSUE TITLE
CRUD breaks single page application approach by doing $window.location.href.

### ISSUE THREAD

**Issue by josvr** [marklogic-community/data-explorer#84]
This is a little task for an Angular guru.

When CRUD is merged (FERR-90, #13 ), the single page application concept is broken. Adhoc-wizard-controller.js contains some "$window.location.href" to force the wizard to go back to the CRUD once the back or insert/update window is pressed. 

This is working however it has 2 disadvantages: (1) the state of the CRUD list is reset (eg if you are viewing the views of query X, then this state is lost) and (2) it looks less polished.

**Comment by josvr** [comment]
I will pick this up

**Comment by josvr** [comment]
Fixed in FERR-90 branch, close this one once FERR-90 is merged.

**Comment by josvr** [comment]
Fixed in #13

**Comment by markschiffner** [comment]
Closed with FERR-90 merge
