### ISSUE TITLE
CRUD only supports ML9

### ISSUE THREAD

**Issue by josvr** [marklogic-community/data-explorer#88]
FERR-90 , #13 is currently only supported by ML9. Rewrite to ML8.

**Comment by josvr** [comment]
as reported by @cskeefer

**Comment by josvr** [comment]
This is fixed in the latest commit of FERR-90 , #13

**Comment by josvr** [comment]
Can be closed after merging FERR-90

**Comment by markschiffner** [comment]
Closed with FERR-90 merge
