### ISSUE TITLE
FERR-66 - JSON Support for the SEARCH Screen

### ISSUE THREAD

**Issue by nlaprell** [marklogic-community/data-explorer#9]
**Original Reporter:**  @josvr  
**Created:** 15/Nov/17 6:06 AM
# Description
*None*

**Blocks:** #8 

# Comments
*None*

**Comment by josvr** [comment]
Pull request created for branch FERR-65. Fixed once merged with master

**Comment by josvr** [comment]
Merged in master. I close this issue now
