### ISSUE TITLE
Investigate the possibilities to remove the global namespaces.xml

### ISSUE THREAD

**Issue by josvr** [marklogic-community/data-explorer#94]
Investigate the possibilities to remove the global namespaces.xml. The global namespaces.xml has some drawbacks (e.g. prefix/namespace conflict). As we have all namespaces already in the query doc, see we can refactor the global namespaces.xml away.

**Comment by josvr** [comment]
Solved in the latest commit to #13 FERR-90 branch

**Comment by markschiffner** [comment]
Closed with FERR-90 merge
