### ISSUE TITLE
Need error message if user does not have correct roles

### ISSUE THREAD

**Issue by markschiffner** [marklogic-community/data-explorer#95]
If a user tries to login with out appropriate roles, the UI login button does nothing.
Needs to let user know to get their user id set up with appropriate roles.

**Comment by markschiffner** [comment]
I did a little testing and it looks like the user must have the data-explorer-ext-amp-role and the data-explorer-modules-role in addition to the data-explorer-wizard-role to be able to login.  The expected behavior is assign either data-explorer-wizard-role or data-explorer-search-role and the application amps as required.

**Comment by markschiffner** [comment]
@vijay - thanks for picking this up.  Since it is highest priority, we should complete this before we cut next release.

**Comment by nlaprell** [comment]
Merged.
