### ISSUE TITLE
SEC-PRIV errors upon trying to login

### ISSUE THREAD

**Issue by josvr** [marklogic-community/data-explorer#99]
The recent master after merging the CRUD branch is throwing SEC-PRIV errors in case of trying to login with the wizard/search user. Reported by @markschiffner and @cskeefer

**Comment by josvr** [comment]
In progress now.

**Comment by damonfeldman** [comment]
@cskeefer is there a workaround?

**Comment by cskeefer** [comment]
@damonfeldman This looks good now. The only security-related issue I'm seeing now is addressed in #131

**Comment by cskeefer** [comment]
Closing since not an issue anymore
